# Sort_Values()

In [2]:
import pandas as pd
oo = pd.read_csv('../../datasets/PandasEssentialTraining/olympics.csv',skiprows=4)
oo.head()



oo.Athlete.sort_values()

651                 AABYE, Edgar
2849       AALTONEN, Arvo Ossian
2852       AALTONEN, Arvo Ossian
7716    AALTONEN, Paavo Johannes
7730    AALTONEN, Paavo Johannes
                  ...
603                   ÖSTMO, Ole
608                   ÖSTMO, Ole
621                   ÖSTMO, Ole
596                   ÖSTMO, Ole
8051           ÖSTRAND, Per-Olof
Name: Athlete, Length: 29216, dtype: object

In [4]:
#The sort_values method has a parameter which have inplace=False, which means that the a new series will be returned.
#If we want to capture these changes we will need to assign the result to a new series
ath = oo.Athlete.sort_values()

In [5]:
#Lets sort by the Edition of the olympics and the Athletes name
oo.sort_values(by=['Edition', 'Athlete'])

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
110,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"team, parallel bars",M,Silver
111,Athens,1896,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"team, parallel bars",M,Silver
48,Athens,1896,Cycling,Cycling Road,"BATTEL, Edward",GBR,Men,individual road race,M,Bronze
...,...,...,...,...,...,...,...,...,...,...
28095,Beijing,2008,Equestrian,Dressage,"ZU-SAYN WITTGENSTEIN, Nathalie",DEN,Women,team,X,Bronze
28819,Beijing,2008,Sailing,Sailing,"ZUBARI, Shahar",ISR,Men,RS:X - Windsurfer,M,Bronze
28977,Beijing,2008,Taekwondo,Taekwondo,"ZUBCIC, Martina",CRO,Women,49 - 57 kg,W,Bronze
28387,Beijing,2008,Gymnastics,Rhythmic G.,"ZUEVA, Natalia",RUS,Women,group competition,W,Gold
29007,Beijing,2008,Tennis,Tennis,"ZVONAREVA, Vera",RUS,Women,singles,W,Bronze

In [6]:
type(oo.sort_values(by=['Edition', 'Athlete']))

pandas.core.frame.DataFrame

In [11]:
oo.sort_values(by=['Edition', 'Athlete'], ascending=False).tail(50)

,City,Edition,Sport,Discipline,Athlete,NOC,Gender,Event,Event_gender,Medal
16,Athens,1896,Athletics,Athletics,"GOULDING, Grantley",GBR,Men,110m hurdles,M,Silver
23,Athens,1896,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800m,M,Bronze
50,Athens,1896,Cycling,Cycling Road,"GOEDRICH, August",GER,Men,individual road race,M,Silver
20,Athens,1896,Athletics,Athletics,"GMELIN, Charles",GBR,Men,400m,M,Bronze
70,Athens,1896,Fencing,Fencing,"GEORGIADIS, Ioannis",GRE,Men,sabre individual,M,Gold
27,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,discus throw,M,Gold
31,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,high jump,M,Silver
34,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,long jump,M,Silver
43,Athens,1896,Athletics,Athletics,"GARRETT, Robert",USA,Men,shot put,M,Gold
86,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Gustav Felix",GER,Men,"team, horizontal bar",M,Gold
101,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Gustav Felix",GER,Men,"team, parallel bars",M,Gold
73,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,horizontal bar,M,Silver
74,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,parallel bars,M,Gold
85,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,"team, horizontal bar",M,Gold
100,Athens,1896,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,"team, parallel bars",M,Gold
51,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
55,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,10km,M,Silver
61,Athens,1896,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,Sprint indivual,M,Bronze
18,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,1500m,M,Gold
24,Athens,1896,Athletics,Athletics,"FLACK, Edwin",AUS,Men,800m,M,Gold
132,Athens,1896,Tennis,Tennis,"FLACK, Edwin",ZZX,Men,doubles,M,Bronze
143,Athens,1896,Weightlifting,Weightlifting,"ELLIOTT, Launceston",GBR,Men,heavyweight - one hand lift,M,Gold
147,Athens,1896,Weightlifting,Weightlifting,"ELLIOTT, Launceston",GBR,Men,heavyweight - two hand lift,M,Silver
2,Athens,1896,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100m freestyle for sailors,M,Bronze
25,Athens,1896,Athletics,Athletics,"DANI, Nandor",HUN,Men,800m,M,Silver
38,Athens,1896,Athletics,Athletics,"DAMASKOS, Evangelos",GRE,Men,pole vault,M,Bronze
15,Athens,1896,Athletics,Athletics,"CURTIS, Thomas",USA,Men,110m hurdles,M,Gold
30,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,high jump,M,Silver
32,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,long jump,M,Bronze
46,Athens,1896,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold
29,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,high jump,M,Gold
33,Athens,1896,Athletics,Athletics,"CLARK, Ellery",USA,Men,long jump,M,Gold
95,Athens,1896,Gymnastics,Artistic G.,"CHRYSAPHIS, Ioannis",GRE,Men,"team, parallel bars",M,Bronze
148,Athens,1896,Wrestling,Wrestling Gre-R,"CHRISTOPOULOS, Stephanos",GRE,Men,open event,M,Bronze
5,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200m freestyle,M,Bronze
8,Athens,1896,Aquatics,Swimming,"CHOROPHAS, Efstathios",GRE,Men,400m freestyle,M,Bronze
4,Athens,1896,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100m freestyle for sailors,M,Silver
66,Athens,1896,Fencing,Fencing,"CALLOT, Henri",FRA,Men,foil individual,M,Silver
84,Athens,1896,Gymnastics,Artistic G.,"BÖCKER, Konrad",GER,Men,"team, horizontal bar",M,Gold
99,Athens,1896,Gymnastics,Artistic G.,"BÖCKER, Konrad",GER,Men,"team, parallel bars",M,Gold
13,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
21,Athens,1896,Athletics,Athletics,"BURKE, Thomas",USA,Men,400m,M,Gold
134,Athens,1896,Tennis,Tennis,"BOLAND, John",ZZX,Men,doubles,M,Gold
140,Athens,1896,Tennis,Tennis,"BOLAND, John",GBR,Men,singles,M,Gold
19,Athens,1896,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500m,M,Silver
48,Athens,1896,Cycling,Cycling Road,"BATTEL, Edward",GBR,Men,individual road race,M,Bronze
111,Athens,1896,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"team, parallel bars",M,Silver
82,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,rope climbing,M,Gold
110,Athens,1896,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"team, parallel bars",M,Silver
7,Athens,1896,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200m freestyle,M,Silver